## Configuration file for DWGettingStarted application.
---
# User login credentails.
login: javaeeeee
# User  password.
password: crimson

#Server configuration.
server:
    applicationConnectors:
        - type: http
          port: 8085
        - type: https
          port: 8443
          keyStorePath: dwstart.keystore
          keyStorePassword: crimson
          validateCerts: false